<?php

namespace Woojin\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function findVisible()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb->select('activity')
            ->from('WoojinStoreBundle:Activity', 'activity')
            ->where($qb->expr()->eq('activity.isHidden', 0))
            ->getQuery()
            ->getResult()
        ;
    }

    public function findHidden()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb->select('activity')
            ->from('WoojinStoreBundle:Activity', 'activity')
            ->where($qb->expr()->eq('activity.isHidden', 1))
            ->getQuery()
            ->getResult()
        ;
    }
}

