<?php

namespace Woojin\StoreBundle\Entity;

/**
 * AuctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuctionRepository extends \Doctrine\ORM\EntityRepository
{
    public function fetchHandlingBelongStore(Store $store)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb->select(array('auction', 'product'))
            ->from('WoojinStoreBundle:Auction', 'auction')
            ->leftJoin('WoojinGoodsBundle:GoodsPassport', 'product')
            ->where($qb->expr()->andX(
                $qb->expr()->in('auction.status', array(
                    Auction::STATUS_ONBOARD,
                    Auction::STATUS_SOLD,
                    Auction::STATUS_ORDER_CANCEL
                )),
                $qb->expr()->eq('auction.createStore', $store)
            ))
            ->getQuery()
            ->getResult()
        ;
    }
}
