<?php

namespace Woojin\StoreBundle\Entity;

/**
 * AuctionPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuctionPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
