<?php

namespace Woojin\StoreBundle\Entity;

/**
 * ShippingOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
