services:
    zipper:
        class: 'Woojin\Utility\Helper\ZipHelper'

    ## 權限判斷服務
    authority.judger:
        class: 'Woojin\Utility\Authority\AuthorityJudger'
        arguments: ['@security.context']

    ## 販售流程鏈
    seller:
        class: 'Woojin\Utility\Que\Sell\Seller'
        arguments: ['@service_container', '@doctrine.orm.entity_manager', '@security.context']

    avenue.notifier:
        class: 'Woojin\Utility\Avenue\Notifier'
        arguments: ['@doctrine.orm.entity_manager', '@swiftmailer.mailer', '@templating', '%mailer_user%']

    ## 優達克斯Excel 產生
    uitox.excel.generator:
        class: 'Woojin\Utility\ExcelGenerator\UitoxExcelGenerator'
        arguments: ['@service_container', '@security.context']

    ## 提供一個避免重複產生 session 的取得 session 方法
    avenue.session:
        class: 'Woojin\Utility\Session\AvenueSession'
        arguments: ['@service_container', '@security.context']

    session.custom:
        class: 'Woojin\Utility\Session\Custom'
        arguments: ['@session', '@doctrine.orm.entity_manager']

    factory.behalf:
        class: 'Woojin\Utility\Factory\Behalf'
        arguments: ['@doctrine.orm.entity_manager', '@service_container']

    facade.product:
        class: 'Woojin\Utility\Facade\Product'
        arguments: ['@doctrine.orm.entity_manager']
    
    factory.order:
        class: 'Woojin\Utility\Factory\OrderFactory'

    factory.product:
        class: 'Woojin\Utility\Factory\ProductFactory'
    
    factory.ope:
        class: 'Woojin\Utility\Factory\OpeFactory'

    factory.img:
        class: 'Woojin\Utility\Factory\ImgFactory'
        arguments: ['@image.handling']

    factory.desimg:
        class: 'Woojin\Utility\Factory\DesimgFactory'
        arguments: ['@image.handling']

    facade.behalf.status:
        class: 'Woojin\Utility\Facade\BehalfStatus'
        arguments: ['@doctrine.orm.entity_manager']

    helper.benefit:
        class: 'Woojin\Utility\Helper\BenefitHelper'
        arguments: ['@session', '@doctrine.orm.entity_manager']

    curler:
        class: 'Woojin\Utility\Helper\CurlHelper'

    yahoo.api.client:
        class: 'Woojin\Utility\YahooApi\Client'
        arguments: ['@curler', '%yahoo_key%', '%yahoo_secret%']
    
    yahoo.syncer:
        class: 'Woojin\Utility\YahooApi\Adapter\Syncer'
        arguments: ['@doctrine.orm.entity_manager', '@yahoo.api.client']
    
    product.finder:
        class: 'Woojin\Service\Finder\ProductFinder'
        arguments: ['@doctrine.orm.entity_manager']
    
    order.finder:
        class: 'Woojin\Service\Finder\OrderFinder'
        arguments: ['@doctrine.orm.entity_manager']

    exporter.stock:
        class: 'Woojin\Service\Exporter\StockExporter'
        arguments: ['@xls.service_xls5', '@security.context']

    exporter.consign:
        class: 'Woojin\Service\Exporter\ConsignExporter'
        arguments: ['@xls.service_xls5']
    
    exporter.profit:
        class: 'Woojin\Service\Exporter\ProfitExporter'
        arguments: ['@xls.service_xls5', '@security.context']

    exporter.uitox:
        class: 'Woojin\Service\Exporter\UitoxExporter'
        arguments: ['@xls.service_xls5', '@security.context', '@zipper']
    
    sculper.clue:
        class: 'Woojin\Service\Sculper\ClueSculper'

    passport.syncer:
        class: 'Woojin\Service\Syncer\PassportSyncer'
        arguments: ['@doctrine.orm.entity_manager']

    resolver.device:
        class: 'Woojin\Utility\Resolver\DeviceResolver'
        arguments: ['@session', '@mobile_detect.mobile_detector']