<?php

namespace Woojin\GoodsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BehalfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BehalfRepository extends EntityRepository
{
}
