<?php

namespace Woojin\OrderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomOpeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomOpeRepository extends EntityRepository
{
}
